# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idm.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tidm.proto\"H\n\x08InfoAuth\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x1e\n\rTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\"#\n\x0fMessageResponse\x12\x10\n\x08response\x18\x01 \x01(\t25\n\tTokenAuth\x12(\n\x0bGenerateJwt\x12\t.InfoAuth\x1a\x0e.TokenResponse2@\n\rTokenValidate\x12/\n\x0bValidateJwt\x12\x0e.TokenResponse\x1a\x10.MessageResponse2>\n\x0cTokenDestroy\x12.\n\nDestroyJwt\x12\x0e.TokenResponse\x1a\x10.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFOAUTH']._serialized_start=13
  _globals['_INFOAUTH']._serialized_end=85
  _globals['_TOKENRESPONSE']._serialized_start=87
  _globals['_TOKENRESPONSE']._serialized_end=117
  _globals['_MESSAGERESPONSE']._serialized_start=119
  _globals['_MESSAGERESPONSE']._serialized_end=154
  _globals['_TOKENAUTH']._serialized_start=156
  _globals['_TOKENAUTH']._serialized_end=209
  _globals['_TOKENVALIDATE']._serialized_start=211
  _globals['_TOKENVALIDATE']._serialized_end=275
  _globals['_TOKENDESTROY']._serialized_start=277
  _globals['_TOKENDESTROY']._serialized_end=339
# @@protoc_insertion_point(module_scope)
